### ISSUE TITLE
Error when installing with PIP

### ISSUE THREAD

**Issue by BNTFryingPan** [beeedy/selfupdate#2]
```
C:\Users\<user>>py -m pip install selfupdate
Collecting selfupdate
  Using cached https://files.pythonhosted.org/packages/c9/0f/63efb90e23f1e856c17d02d1a3b76097601bddc6cd654024a2511e4d5851/selfupdate-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\<user>\AppData\Local\Temp\pip-install-cl5cuatz\selfupdate\setup.py", line 10, in <module>
        import selfupdate
    ModuleNotFoundError: No module named 'selfupdate'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\<user>\AppData\Local\Temp\pip-install-cl5cuatz\selfupdate\
```

I get this error when i run PIP to install the module. This occurs both in the Command Prompt and the Powershell

**Comment by morpheus65535** [comment]
Same here!

**Comment by morpheus65535** [comment]
Seems to be for Python 3... Are you trying it from python 2.7 like me?

**Comment by BNTFryingPan** [comment]
i use python 3.6

**Comment by morpheus65535** [comment]
Oh... good luck than! I had to use something else.

**Comment by NuclearManD** [comment]
@beeedy Hello, I am having the same issue here.  Are you going to merge in the PR and put it on pip or should I use another package or method?  It's been over a year now :P Thanks

**Comment by Zi7ar21** [comment]
WE NEED THIS REPOSITORY HELP

**Comment by beeedy** [comment]
Is this issue good to close?

**Comment by erfantkerfan** [comment]
@beeedy any look updating PIP repo?

**Comment by gregoriopellegrino** [comment]
any news?

**Comment by erfantkerfan** [comment]
pip package still hasn't been updated? is there a problem? @beeedy

**Comment by erfantkerfan** [comment]
the package is now **updated** in pip
